### ISSUE TITLE
keyword argument "points" does not work for `ode45` (???)

### ISSUE THREAD

**Issue by Datseris** [JuliaLang/ODE.jl#100]
Hello,

I am using ODE, and specifically I call ODE.ode45 as:
`t, var_vec = ODE.ode45(derivatives, var_0, t; abstol = 1e-10)` 

However this does not return the same `t` vector. Reading your documentation, you give a keyword argument "points", which I am not quite sure if I use it correctly.

I use the code
`t, var_vec = ODE.ode45(derivatives, var_0, t; abstol = 1e-10, points = "specified")`
like one would do in python, but it doesn't work.
It gives off error when I use it like that:
` LoadError: Unrecognized option points==specified
 in oderk_adapt at C:\Users\migos\.julia\v0.4\ODE\src\runge_kutta.jl:276
 in ode45_dp at C:\Users\migos\.julia\v0.4\ODE\src\runge_kutta.jl:212
 in include_string at loading.jl:282
 in include_string at C:\Users\migos\.julia\v0.4\CodeTools\src\eval.jl:32
 in anonymous at C:\Users\migos\.julia\v0.4\Atom\src\eval.jl:84
 in withpath at C:\Users\migos\.julia\v0.4\Requires\src\require.jl:37
 in withpath at C:\Users\migos\.julia\v0.4\Atom\src\eval.jl:53
 [inlined code] from C:\Users\migos\.julia\v0.4\Atom\src\eval.jl:83
 in anonymous at task.jl:58
while loading C:\Users\migos\Dropbox\Antidots in Graphene\Julia Codes\Integrator.jl, in expression starting on line 186 `

What am I doing wrong?
The documentation that you have at the API is very unclear...

**Comment by acroy** [comment]
I think the documentation is pretty clear about that: `points=:specified` gives results only for the times in `tspan`, while `points=:all` also gives results at intermediate times used by the solver. Note that Julia uses symbols with a prefix `:` instead of strings.

**Comment by Datseris** [comment]
Thank you, now it works, you are completely right. The doc confused me because it used once `=` and then two `==` . Of course, I am learning Julia that is why I do not understood this one. Could you please point me to the Julia documentation that says that Julia uses " symbols with a prefix : instead of strings " ? Because I think this is what made me not understand the documentation. 
Thank you once again!

**Comment by acroy** [comment]
You are welcome. I think I should have written "in Julia one **often** uses symbols instead of strings" (see [docs on symbols](http://docs.julialang.org/en/release-0.4/manual/metaprogramming/?highlight=symbol#symbols)). Of course keywords may also be strings in general, but here we use symbols.
