### ISSUE TITLE
Step size grew too small

### ISSUE THREAD

**Issue by Phelipe** [JuliaLang/ODE.jl#58]
I'm having trouble with the error "Step size Grew too small" . How can I modify the minimum step to solve the problem?
Thank you!

**Comment by acroy** [comment]
Unfortunately, there is no way to control the minimum step size with the current version. I just created #59, which will allow you to do this. In the meantime you might try `ode23s` on the master branch, which has a smaller minimum step (#53).

**Comment by Phelipe** [comment]
Thank you for this solution, is perfect.
