### ISSUE TITLE
Support of SDE Solvers?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/ODE.jl#64]
Hi,
  I am recently joining the Julia train and I have a good amount of experience with stochastic ODE/PDE solvers. I was thinking of adding this functionality to Julia, though I was wondering if this should be considered as a package separate from the ODE solvers or be part of it itself. I would like to hear your thoughts on this.

**Comment by acroy** [comment]
I just wanted to point out SDE.jl (see also a [recent discussion on julia-users](https://groups.google.com/forum/?nomobile=true#!searchin/julia-users/stochastic/julia-users/AR937Q1mdvw/9m7JUjVVh0QJ)) but you were faster.  There is also [Ito.jl](https://github.com/aviks/Ito.jl), which contains some stochastic solvers. Nevertheless, personally I think it would be great to have a package dedicated to stochastic ODEs/PDE. If you have experience with such solvers, creating a package might be a good way to learn more about Julia ...

**Comment by ViralBShah** [comment]
I have been thinking for a while if there should be an organization for various differential equations. ODEs, PDEs, DAEs, SDEs, etc.

**Comment by acroy** [comment]
An org would be useful, also to synchronize APIs to some extend.

**Comment by ChrisRackauckas** [comment]
Hey, I wanted to let you guys know that I did come back to Julia and in the last few months wrote a whole suite for ODEs, PDEs, SDEs, SPDEs. I even have some "very new" algorithms since SDEs/SPDEs is what I am doing my PhD research in. You can find it at [DifferentialEquations.jl](https://github.com/ChrisRackauckas/DifferentialEquations.jl). 

I dropped the MATLAB interface because I think using types/dispatches is a more Julian API, and it's easier to extend without breaking past functionality. Everything has numerous amounts of tests to ensure accuracy. I'll be releasing (/announcing) it soon. 

Let me know what you guys think!
