### ISSUE TITLE
ode45 tries to evaluate function outside of provided range

### ISSUE THREAD

**Issue by afniedermayer** [JuliaLang/ODE.jl#66]
This seems to be a new bug introduced by a recent commit, since I have code that used to work a few days ago and now throws an exception. I managed to narrow down the problem to the following.

Consider solving for `F(x)=1-(1-x)^1.5` on [0,1] with boundary condition `F(1)=1`. To avoid numerical problems at x=1, replace 1 with 0.99:
```julia
using ODE
diff_eq(x,F) = try
                 1.5*(1-x).^(.5)
               catch err
                 @show x
                 throw(err)
               end
ode45(diff_eq, .99, [.99,0.0])
```
This gives this output
```
x => 1.056
ERROR: DomainError
 in diff_eq at none:5
 in hinit at /home/niedermayer/.julia/v0.3/ODE/src/ODE.jl:39
 in oderkf at /home/niedermayer/.julia/v0.3/ODE/src/ODE.jl:85
 in ode45_dp at /home/niedermayer/.julia/v0.3/ODE/src/ODE.jl:190
```
The problem seems to be that `ode45` tries to evaluate the function at x=1.056, which is outside of the range [0,0.99].

**Comment by acroy** [comment]
Thanks for reporting this. The issue is that the initial step estimator (`hinit` in your backtrace) doesn't take the integration direction into account and this is where we evaluate outside the given range. For a quick fix, you can use `ode45(diff_eq, .99, [.99,0.0], initstep=1/10)` with `1/10` adjusted to your problem.

**Comment by acroy** [comment]
@afniedermayer : This should now be fixed on master (via #67). Would be great if you could test with your code.

**Comment by tlycken** [comment]
(You might need to `Pkg.checkout("ODE")` to get the latest changes...)

**Comment by afniedermayer** [comment]
My code works again! Thanks! 

(BTW, I didn't need `Pkg.checkout("ODE")`, `Pkg.update()` was sufficient. I guess this means that changes to master automatically become part of the "current stable version". I don't know whether that is intended.)

**Comment by tlycken** [comment]
(@afniedermayer No new version has been tagged since this was pushed, so you were probably already on the latest master then. What does `Pkg.status()` tell you about ODE.jl?)

**Comment by afniedermayer** [comment]
@tlycken , thanks. You were right, I was already on the latest master, `Pkg.status()` tells
```
 - ODE                           0.1.2+             master
```
I don't remember, but I must have checked out the master branch at some point in the past.
