### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by crbinz** [JuliaLang/ODE.jl#75]
Is it possible to tag a new release for this project? I've been using the new Runge-Kutta solver (particularly with the keyword arguments support), and it would help to have a version I can specify in my REQUIRE. Thanks.

**Comment by mauro3** [comment]
I think the idea was to tag a new release after the merge of the new R-K solver, maybe it was just forgotten?

**Comment by acroy** [comment]
The question is if we should tag it as v"0.3.0" or v"0.2.1" (v"0.2.0" points to the old implementation)?

**Comment by tlycken** [comment]
The new solvers have changed the api, right? Then I think `v0.3.0` is appropriate.

**Comment by acroy** [comment]
I think they haven't. For example, Mauro had to put in some effort to support those "scalar-like types" as we had them before.

**Comment by mauro3** [comment]
The interface of the low-level function changed somewhat:
```
function oderk_adapt{N,S}(fn, y0::AbstractVector, tspan, btab_::TableauRKExplicit{N,S};
                          reltol = 1.0e-5, abstol = 1.0e-8,
                          norm=Base.norm,
                          minstep=abs(tspan[end] - tspan[1])/1e18,
                          maxstep=abs(tspan[end] - tspan[1])/2.5,
                          initstep=0.,
                          points=:all
                          )
```
vs before
```
function oderkf(F, x0, tspan, p, a, bs, bp; reltol = 1.0e-5, abstol = 1.0e-8,
                                            norm=Base.norm,
                                            minstep=abs(tspan[end] - tspan[1])/1e9,
                                            maxstep=abs(tspan[end] - tspan[1])/2.5,
                                            initstep=0.)
```
For the exported functions this only adds `points`.  For some reason `ode23` is not exported anymore, however, this is probably a bug and should be fixed.

**Comment by acroy** [comment]
@mauro3 : I just added the export of `ode23` which got lost somehow.

If there are no objections I will tag the current master as v"0.2.1" instead of v"0.3.0" since the API  hasn't really changed.

**Comment by mauro3** [comment]
Yep, that sounds good.

**Comment by yuyichao** [comment]
Is the tagging happenning? Would be nice to get rid of those annoy deprecation warnings...

**Comment by yuyichao** [comment]
Given https://github.com/JuliaLang/ODE.jl/pull/76#issuecomment-141017394 I just went ahead and [tagged 0.2.1](https://github.com/JuliaLang/METADATA.jl/pull/3451)

**Comment by mauro3** [comment]
Thanks
