### ISSUE TITLE
ODE23s maxstep

### ISSUE THREAD

**Issue by hvillegaspico** [JuliaLang/ODE.jl#77]
maxstep option was removed from ODE 23s.
Can it be reintegrated? It is useful to have it.

**Comment by acroy** [comment]
As far as I can see it is still there (on master which should be v0.2.1). Could you describe the problem/error you see?

**Comment by hvillegaspico** [comment]
Yes you are right, the master file has the option. However, when I "add" the package to my computer, I get a version of the ODE23s with the following code:

function ode23s(F, y0, tspan; reltol = 1.0e-5, abstol = 1.0e-8,
                                                jacobian=nothing,
                                                points=:all,
                                                norm=Base.norm)

    # select method for computing the Jacobian
    if typeof(jacobian) == Function
        jac = jacobian
    else
        # fallback finite-difference
        jac = (t, y)->fdjacobian(F, y, t)
    end
.....
Evidently, this code does not have a maxstep parameter; therefore, when I try to invoke ode23s with a parameter named maxstep, Julia complains saying the keyword argument maxstep is unrecognized.

**Comment by acroy** [comment]
Have you done `Pkg.update()` first? What does `Pkg.status()` say? (Needless to say that it works for me)

**Comment by hvillegaspico** [comment]
I ran package update.
When running Pkg.status() I have 

ODE                           0.1.2              054769c1 (dirty)

for ODE. The code of the package remained the same.
I removed the folder of the package in my local repository .julia and reinstalled the package.
Then, the status of the package becomes:
ODE                           0.2.1
It is a weird behavior, but he issue is fixed.

**Comment by tlycken** [comment]
The `(dirty)` indicates that you had changed something in that directory without saving them in git; thus, `Pkg.update()` didn't actually update ODE.jl, to avoid overwriting any changes you wanted to save. When you deleted the folder, you also removed your changes, so `Pkg.add("ODE")` could now add a fresh clone and get the latest version. (This behavior is consistent over any package, and not just for ODE.jl.)
