### ISSUE TITLE
Optional Arguments

### ISSUE THREAD

**Issue by DRNbw** [JuliaLang/ODE.jl#90]
Is there a way to pass other arguments to the function being solved?

tout, yout = odeXX(F, y0, tspan; keywords...)

function F (t, y, args)
  ...
end

**Comment by mauro3** [comment]
Make a closure:
```
args = (4,5) # whatever
FF(t,y) = F(t,y,args)
tout, yout = odeXX(FF, y0, tspan; keywords...)
```

**Comment by DRNbw** [comment]
Makes sense, thanks.
